/************* The Complete Oracle SQL Bootcamp *************
 * Author  : Oracle Master Training                         *
 * Course  : The Complete Oracle SQL Bootcamp               *
 * Lecture : Oracle IDENTITY Column                         *
 ************************************************************/

CREATE TABLE temp (ID NUMBER GENERATED AS IDENTITY, 
                   text VARCHAR2(100));

DROP TABLE temp;                   
CREATE TABLE temp (ID NUMBER GENERATED ALWAYS AS IDENTITY, 
                   text VARCHAR2(100));
                   
DROP TABLE temp;
CREATE TABLE temp (ID NUMBER GENERATED BY DEFAULT AS IDENTITY, 
                   text VARCHAR2(100));

DROP TABLE temp;
CREATE TABLE temp (ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
                   text VARCHAR2(100));

DROP TABLE temp;
CREATE TABLE temp (ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 50 INCREMENT BY 3, 
                   text VARCHAR2(100));

INSERT INTO temp (ID, text) VALUES (1,'Test with 1');
INSERT INTO temp (ID, text) VALUES (20,'Test with 20');
INSERT INTO temp (ID, text) VALUES (NULL,'Test with NULL');
INSERT INTO temp (text) VALUES ('Test with No Value');
SELECT * FROM temp;

SELECT * FROM user_objects WHERE object_name = 'ISEQ$$_74510';
SELECT * FROM user_sequences WHERE sequence_name = 'ISEQ$$_74510';
SELECT ISEQ$$_74510.NEXTVAL FROM dual;

DROP TABLE temp;
PURGE RECYCLEBIN;